/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Idir' at '15/07/19 16:36' with Gradle 2.14.1
 *
 * @author Idir, @date 15/07/19 16:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
